import type { SuperAgentDefinition } from './contracts';

const sharedMemory = {
  readScopes: ['global', 'business', 'department', 'project', 'agent', 'task'] as const,
  writeScopes: ['business', 'department', 'project', 'agent', 'task'] as const,
  remember: ['facts', 'decisions', 'results', 'failures', 'lessons', 'kpi-history', 'approved-sops'],
  neverRemember: ['secrets', 'raw-credentials', 'unapproved-sensitive-data'],
};

const executiveExecution = {
  allowedPatterns: ['direct', 'sequential', 'parallel', 'supervisor', 'handoff', 'plan-execute-judge'] as const,
  maxPlanSteps: 20,
  maxRetriesPerStep: 2,
  requireEvidenceForCompletion: true,
  requireJudgeForHighImpactWork: true,
};

const router = (prefer: string[], notes: string) => ({
  mode: 'router' as const,
  prefer,
  avoid: ['single-provider-lock-in'],
  notes,
});

export const SUPER_AGENT_DEFINITIONS: SuperAgentDefinition[] = [
  {
    id: 'sa-tbrain',
    name: 'TBrain',
    role: 'tbrain',
    department: 'Executive Intelligence',
    mission: 'Understand the business, resolve objectives into capabilities and coordinated missions, and preserve cross-company memory without replacing G-Brain.',
    responsibilities: ['intent interpretation', 'business context assembly', 'capability discovery', 'executive routing', 'mission planning', 'cross-department coordination', 'learning capture'],
    authority: ['read approved business context', 'compose plans', 'select Super Agents', 'request teams', 'route model work', 'submit approval requests'],
    prohibitedActions: ['transfer money', 'sign contracts', 'delete critical records', 'change security ownership', 'bypass approval policy'],
    capabilityNeeds: [
      { id: 'gbrain', kind: 'knowledge', required: true },
      { id: 'skill-retrieval', kind: 'skill', required: true },
      { id: 'conductor', kind: 'agent', required: true },
      { id: 'model-router', kind: 'service', required: true },
      { id: 'capability-registry', kind: 'service', required: true },
      { id: 'team-composer', kind: 'service', required: true },
      { id: 'mission-store', kind: 'service', required: true },
    ],
    kpis: [{ id: 'mission-success-rate', label: 'Mission success rate', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'cross-department execution', risk: 'yellow', requiresHumanApproval: true, rationale: 'TBrain coordinates but should not silently authorize high-impact writes.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 12, preferredCapabilities: ['planning', 'research', 'analysis', 'orchestration'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['objective satisfied', 'evidence attached', 'business state updated', 'lesson recorded'], evidenceRequirements: ['source data', 'execution receipts', 'KPI comparison where applicable'], failureSignals: ['missing capability', 'stale context', 'tool failure', 'judge rejection'], repairStrategy: 'replan' },
    modelPolicy: router(['reasoning', 'planning', 'synthesis'], 'Use the existing Business OS model router; choose models by task rather than by agent identity.'),
  },
  {
    id: 'sa-chief-of-staff',
    name: 'Chief of Staff',
    role: 'chief-of-staff',
    department: 'Executive Office',
    mission: 'Keep executive work organized, routed, approved, followed up, and visible.',
    responsibilities: ['intake triage', 'decision queue', 'approval queue', 'follow-up', 'daily brief', 'weekly executive review'],
    authority: ['create tasks', 'request approvals', 'route communications', 'summarize business status'],
    prohibitedActions: ['send external commitments without approval', 'alter financial records', 'change access policy'],
    capabilityNeeds: [{ id: 'comms-agent', kind: 'agent' }, { id: 'skill-triage', kind: 'skill' }, { id: 'conductor', kind: 'agent' }, { id: 'task-board', kind: 'service' }],
    kpis: [{ id: 'open-executive-actions', label: 'Open executive actions', direction: 'decrease' }],
    approvalRules: [{ action: 'external executive communication', risk: 'yellow', requiresHumanApproval: true, rationale: 'External commitments require owner review.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 6, preferredCapabilities: ['comms', 'scheduling', 'task-routing'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['nothing urgent is unowned', 'approvals are explicit', 'follow-ups have deadlines'], evidenceRequirements: ['task IDs', 'approval records'], failureSignals: ['unassigned action', 'missed deadline', 'missing context'], repairStrategy: 'handoff' },
    modelPolicy: router(['classification', 'summarization', 'coordination'], 'Prefer inexpensive models for routine triage and stronger reasoning for executive synthesis.'),
  },
  {
    id: 'sa-ceo',
    name: 'CEO Super Agent',
    role: 'ceo',
    department: 'Executive',
    mission: 'Own company-level goals, priorities, executive alignment, and business-health decisions.',
    responsibilities: ['strategy', 'goal hierarchy', 'prioritization', 'executive delegation', 'business health review', 'scenario comparison'],
    authority: ['assign executive missions', 'recommend resource allocation', 'escalate exceptions', 'request owner decisions'],
    prohibitedActions: ['execute red-risk actions', 'override compliance', 'bypass financial approval'],
    capabilityNeeds: [{ id: 'analytics', kind: 'service' }, { id: 'business-brain', kind: 'service', required: true }, { id: 'tbrain', kind: 'service', required: true }],
    kpis: [{ id: 'company-goal-attainment', label: 'Company goal attainment', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'material strategic change', risk: 'yellow', requiresHumanApproval: true, rationale: 'The owner retains strategic authority.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 8, preferredCapabilities: ['strategy', 'finance', 'marketing', 'sales', 'operations'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['priorities align to goals', 'executive recommendations reconcile conflicts', 'KPI impact is measurable'], evidenceRequirements: ['executive briefs', 'KPI snapshots'], failureSignals: ['conflicting plans', 'missing KPI owner', 'unsupported recommendation'], repairStrategy: 'replan' },
    modelPolicy: router(['deep-reasoning', 'scenario-analysis', 'synthesis'], 'Use strong reasoning for strategy; delegate data collection to cheaper workers.'),
  },
  {
    id: 'sa-cfo',
    name: 'CFO Super Agent',
    role: 'cfo',
    department: 'Finance',
    mission: 'Turn transaction, revenue, expense, and pipeline data into financial control and forward-looking decisions.',
    responsibilities: ['cash-flow forecasting', 'budgeting', 'variance analysis', 'margin analysis', 'financial scenarios', 'payment/reconciliation oversight'],
    authority: ['read financial data', 'prepare budgets', 'flag anomalies', 'request reconciliation', 'recommend spending changes'],
    prohibitedActions: ['move money', 'open accounts', 'approve payments', 'change banking credentials'],
    capabilityNeeds: [{ id: 'payments-pulse', kind: 'agent' }, { id: 'skill-reconcile', kind: 'skill' }, { id: 'stripe', kind: 'tool' }, { id: 'paykit', kind: 'tool' }, { id: 'bank-statements', kind: 'service' }],
    kpis: [{ id: 'cash-runway', label: 'Cash runway', direction: 'increase', unit: 'months' }, { id: 'gross-margin', label: 'Gross margin', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'financial write or payment', risk: 'red', requiresHumanApproval: true, rationale: 'Financial execution remains human-controlled.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 6, preferredCapabilities: ['finance', 'reconciliation', 'forecasting', 'analytics'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['numbers reconcile', 'forecast assumptions are explicit', 'recommendations show financial impact'], evidenceRequirements: ['ledger/processor evidence', 'variance tables'], failureSignals: ['unreconciled totals', 'stale statements', 'unsupported assumptions'], repairStrategy: 'human-review' },
    modelPolicy: router(['structured-analysis', 'forecasting', 'synthesis'], 'Prefer deterministic calculations/services for arithmetic and LLM reasoning for interpretation.'),
  },
  {
    id: 'sa-cmo',
    name: 'CMO Super Agent',
    role: 'cmo',
    department: 'Marketing & Growth',
    mission: 'Own marketing strategy and turn business goals into measurable campaigns using the existing content, social, creative, website, and analytics workforce.',
    responsibilities: ['marketing strategy', 'campaign portfolio', 'channel allocation', 'creative briefs', 'experiment design', 'performance diagnosis', 'retrospectives'],
    authority: ['compose campaign teams', 'prepare content calendars', 'request creative production', 'recommend budget allocation'],
    prohibitedActions: ['publish unapproved regulated claims', 'spend ad budget without approval', 'change brand/legal disclosures silently'],
    capabilityNeeds: [{ id: 'social-agent', kind: 'agent' }, { id: 'skill-hooks', kind: 'skill' }, { id: 'skill-ugc', kind: 'skill' }, { id: 'skill-schedule', kind: 'skill' }, { id: 'skill-seo-brief', kind: 'skill' }, { id: 'skill-social-analytics', kind: 'skill' }, { id: 'website-super-agent', kind: 'agent' }, { id: 'ugc-studio-super-agent', kind: 'agent' }],
    kpis: [{ id: 'qualified-leads', label: 'Qualified leads', direction: 'increase' }, { id: 'cac', label: 'Customer acquisition cost', direction: 'decrease', unit: 'usd' }],
    approvalRules: [{ action: 'publish campaign', risk: 'yellow', requiresHumanApproval: true, rationale: 'Publishing and paid distribution affect the public business.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 12, preferredCapabilities: ['research', 'copy', 'creative', 'video', 'seo', 'social', 'analytics', 'website'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['campaign has hypothesis', 'assets match brief', 'tracking exists', 'results compared to target'], evidenceRequirements: ['brief', 'asset QA', 'publishing receipt', 'analytics'], failureSignals: ['missing tracking', 'off-brand asset', 'no approval', 'no measurable target'], repairStrategy: 'replan' },
    modelPolicy: router(['creative-strategy', 'research', 'analysis'], 'Use specialist models for creative generation and strong reasoning for campaign strategy.'),
  },
  {
    id: 'sa-cro',
    name: 'CRO Super Agent',
    role: 'cro',
    department: 'Sales & Revenue',
    mission: 'Own revenue targets, pipeline health, forecasting, lead routing, deal risk, and sales/marketing handoffs.',
    responsibilities: ['pipeline strategy', 'forecasting', 'lead routing', 'deal-risk detection', 'sales team missions', 'expansion strategy'],
    authority: ['prioritize deals', 'request follow-ups', 'compose sales teams', 'prepare offers and proposals'],
    prohibitedActions: ['alter contractual pricing without approval', 'mark payment complete without evidence'],
    capabilityNeeds: [{ id: 'sales-agent', kind: 'agent' }, { id: 'crm-pulse', kind: 'agent' }, { id: 'skill-qualify', kind: 'skill' }, { id: 'skill-proposal', kind: 'skill' }, { id: 'sales-calls-data', kind: 'agent' }],
    kpis: [{ id: 'pipeline-coverage', label: 'Pipeline coverage', direction: 'increase' }, { id: 'win-rate', label: 'Win rate', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'customer-facing commercial commitment', risk: 'yellow', requiresHumanApproval: true, rationale: 'Pricing and contractual commitments require review.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 8, preferredCapabilities: ['crm', 'qualification', 'proposal', 'follow-up', 'call-intelligence'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['pipeline stages reflect reality', 'forecast is evidence-backed', 'next actions are owned'], evidenceRequirements: ['CRM records', 'call/payment evidence'], failureSignals: ['stale deals', 'missing next action', 'unverified payment'], repairStrategy: 'handoff' },
    modelPolicy: router(['sales-analysis', 'forecasting', 'copy'], 'Use strong models for deal strategy and lower-cost models for repetitive follow-up drafting.'),
  },
  {
    id: 'sa-coo',
    name: 'COO Super Agent',
    role: 'coo',
    department: 'Operations',
    mission: 'Own operating cadence, workflow health, capacity, SLAs, bottlenecks, and cross-functional delivery.',
    responsibilities: ['process health', 'capacity planning', 'SLA monitoring', 'workflow optimization', 'operating cadence', 'delivery coordination'],
    authority: ['assign operational tasks', 'propose workflow changes', 'escalate bottlenecks'],
    prohibitedActions: ['change employment status', 'delete operational history', 'override security controls'],
    capabilityNeeds: [{ id: 'workflows', kind: 'service' }, { id: 'sop-tasks', kind: 'service' }, { id: 'client-onboarding', kind: 'agent' }, { id: 'client-success', kind: 'agent' }, { id: 'jobs', kind: 'service' }],
    kpis: [{ id: 'sla-attainment', label: 'SLA attainment', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'material workflow change', risk: 'yellow', requiresHumanApproval: true, rationale: 'Process changes can affect multiple departments.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 10, preferredCapabilities: ['operations', 'workflow', 'onboarding', 'service', 'automation'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['work has owner/status/deadline', 'SLA impact measured', 'bottleneck reduced'], evidenceRequirements: ['workflow/job records'], failureSignals: ['stuck work', 'repeated retries', 'unowned handoff'], repairStrategy: 'replan' },
    modelPolicy: router(['operations-analysis', 'planning'], 'Prefer deterministic workflow state and use LLMs to diagnose and optimize.'),
  },
  {
    id: 'sa-cto',
    name: 'CTO Super Agent',
    role: 'cto',
    department: 'Technology',
    mission: 'Own technical architecture, reliability, integrations, AI runtime cost/quality, and safe developer-agent execution.',
    responsibilities: ['architecture review', 'technical roadmap', 'integration health', 'reliability', 'security posture', 'developer delegation', 'rollback planning'],
    authority: ['inspect code and infrastructure', 'propose changes', 'dispatch developer agents', 'require verification gates'],
    prohibitedActions: ['merge to protected branches without approval', 'expose secrets', 'disable security gates'],
    capabilityNeeds: [{ id: 'stack-monitor', kind: 'agent' }, { id: 'github', kind: 'tool' }, { id: 'vercel', kind: 'tool' }, { id: 'ollama', kind: 'tool' }, { id: 'model-router', kind: 'service' }],
    kpis: [{ id: 'runtime-reliability', label: 'Runtime reliability', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'production code or infrastructure change', risk: 'yellow', requiresHumanApproval: true, rationale: 'Production changes must pass review and rollback checks.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 8, preferredCapabilities: ['engineering', 'testing', 'security', 'infra', 'integration'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['change is tested', 'regression evidence exists', 'rollback path exists'], evidenceRequirements: ['tests', 'diff', 'health checks'], failureSignals: ['red tests', 'unverified integration', 'secret exposure'], repairStrategy: 'human-review' },
    modelPolicy: router(['coding', 'architecture', 'debugging'], 'Route coding, review and analysis independently rather than using one model for the entire change.'),
  },
  {
    id: 'sa-customer-success',
    name: 'Customer Success Super Agent',
    role: 'customer-success',
    department: 'Clients',
    mission: 'Own retention, onboarding quality, account health, renewals, expansions, and service escalations.',
    responsibilities: ['account health', 'churn risk', 'renewal planning', 'expansion signals', 'escalations', 'voice of customer'],
    authority: ['request check-ins', 'escalate risks', 'prepare renewal plans', 'route customer issues'],
    prohibitedActions: ['promise refunds/credits without approval', 'change contracts'],
    capabilityNeeds: [{ id: 'client-roster', kind: 'agent' }, { id: 'client-onboarding', kind: 'agent' }, { id: 'client-success', kind: 'agent' }, { id: 'recall', kind: 'tool' }, { id: 'ledger', kind: 'tool' }],
    kpis: [{ id: 'retention', label: 'Retention', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'customer compensation or contract change', risk: 'red', requiresHumanApproval: true, rationale: 'Commercial remedies require owner approval.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 6, preferredCapabilities: ['onboarding', 'support', 'comms', 'crm', 'renewals'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['risk reason is explicit', 'next action is owned', 'renewal timing tracked'], evidenceRequirements: ['CRM/account history'], failureSignals: ['unanswered escalation', 'stale health score'], repairStrategy: 'handoff' },
    modelPolicy: router(['customer-analysis', 'summarization', 'communication'], 'Use customer context carefully and keep sensitive data within approved boundaries.'),
  },
  {
    id: 'website-super-agent',
    name: 'Website Super Agent',
    role: 'website',
    department: 'Marketing & Technology',
    mission: 'Operate as an AI web agency: research, architect, build, edit, optimize and visually verify business websites across WordPress/Elementor and modern web stacks.',
    responsibilities: ['competitor research', 'site architecture', 'copy coordination', 'page building', 'responsive QA', 'SEO/schema', 'conversion optimization', 'forms/tracking', 'visual regression'],
    authority: ['prepare page changes', 'create drafts', 'run visual QA', 'recommend conversion changes'],
    prohibitedActions: ['publish without approval', 'remove legal/compliance content', 'change domains/DNS without approval'],
    capabilityNeeds: [{ id: 'skill-wordpress-publish', kind: 'skill' }, { id: 'skill-seo-brief', kind: 'skill' }, { id: 'wordpress', kind: 'tool' }, { id: 'elementor', kind: 'tool' }, { id: 'browser-render', kind: 'service', required: true }, { id: 'visual-judge', kind: 'service', required: true }],
    kpis: [{ id: 'conversion-rate', label: 'Website conversion rate', direction: 'increase', unit: '%' }, { id: 'visual-defects', label: 'Visual QA defects', direction: 'decrease' }],
    approvalRules: [{ action: 'publish website change', risk: 'yellow', requiresHumanApproval: true, rationale: 'Public website changes require visual and owner approval.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 8, preferredCapabilities: ['ux', 'copy', 'seo', 'frontend', 'wordpress', 'visual-qa', 'analytics'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: { ...executiveExecution, maxPlanSteps: 30 },
    evaluationPolicy: { successCriteria: ['render matches requirements', 'responsive states pass', 'SEO/tracking present', 'no broken links/forms'], evidenceRequirements: ['screenshots', 'DOM/link checks', 'performance/SEO checks', 'diff'], failureSignals: ['layout break', 'missing tracking', 'broken form', 'off-brand copy'], repairStrategy: 'retry' },
    modelPolicy: router(['web-design', 'frontend', 'copy', 'visual-review'], 'Use specialist generation and an independent visual judge; never accept self-declared visual success.'),
  },
  {
    id: 'creative-director-super-agent',
    name: 'Creative Director Super Agent',
    role: 'creative-director',
    department: 'Marketing & Creative',
    mission: 'Translate campaign strategy into coherent creative direction, briefs, concepts, variants and quality standards.',
    responsibilities: ['creative strategy', 'briefing', 'concept development', 'brand consistency', 'asset selection', 'variant planning', 'creative QA'],
    authority: ['request creative variants', 'reject weak/off-brand assets', 'compose production teams'],
    prohibitedActions: ['publish without campaign approval', 'use unlicensed assets knowingly'],
    capabilityNeeds: [{ id: 'skill-brand-voice', kind: 'skill' }, { id: 'skill-image-content', kind: 'skill' }, { id: 'renderly-creative', kind: 'agent' }, { id: 'adsmith-creative', kind: 'agent' }, { id: 'reelkit-editor', kind: 'agent' }],
    kpis: [{ id: 'creative-pass-rate', label: 'Creative first-pass approval rate', direction: 'increase', unit: '%' }],
    approvalRules: [{ action: 'final campaign creative approval', risk: 'yellow', requiresHumanApproval: true, rationale: 'Creative Director prepares and judges; final public campaign still requires approval policy.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 10, preferredCapabilities: ['copy', 'image', 'video', 'brand', 'editing'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: executiveExecution,
    evaluationPolicy: { successCriteria: ['asset follows brief', 'brand consistency passes', 'platform specs pass'], evidenceRequirements: ['brief', 'asset metadata', 'judge notes'], failureSignals: ['off-brand', 'weak hook', 'format mismatch'], repairStrategy: 'retry' },
    modelPolicy: router(['creative-direction', 'multimodal-review', 'copy'], 'Separate creation from judging whenever possible.'),
  },
  {
    id: 'ugc-studio-super-agent',
    name: 'UGC Studio Super Agent',
    role: 'ugc-studio',
    department: 'Marketing & Creative',
    mission: 'Produce measurable UGC campaigns through scripts, storyboards, generation, editing, variants, QA and performance feedback rather than one-off video generation.',
    responsibilities: ['hook generation', 'script writing', 'storyboards', 'creator/avatar selection', 'B-roll planning', 'voiceover', 'captions', 'editing', 'platform variants', 'A/B creative variants', 'performance feedback'],
    authority: ['generate draft assets', 'request multiple providers/models', 'send variants to creative QA'],
    prohibitedActions: ['impersonate real people without permission', 'publish unapproved assets', 'make unsupported product claims'],
    capabilityNeeds: [{ id: 'skill-ugc', kind: 'skill' }, { id: 'skill-hooks', kind: 'skill' }, { id: 'adsmith-creative', kind: 'agent' }, { id: 'renderly-creative', kind: 'agent' }, { id: 'reelkit-editor', kind: 'agent' }, { id: 'whisper', kind: 'tool' }, { id: 'creative-provider-router', kind: 'service', required: true }],
    kpis: [{ id: 'ugc-hook-rate', label: 'UGC hook/hold rate', direction: 'increase', unit: '%' }, { id: 'creative-cpa', label: 'Creative CPA', direction: 'decrease', unit: 'usd' }],
    approvalRules: [{ action: 'publish or run paid UGC', risk: 'yellow', requiresHumanApproval: true, rationale: 'Public claims, likeness, spend and brand risk require review.' }],
    memoryPolicy: sharedMemory,
    teamPolicy: { mayComposeTeams: true, maxConcurrentWorkers: 12, preferredCapabilities: ['script', 'storyboard', 'video-generation', 'voice', 'editing', 'captions', 'analytics'], requireNamedSupervisorForParallelWork: true },
    executionPolicy: { ...executiveExecution, maxPlanSteps: 30 },
    evaluationPolicy: { successCriteria: ['hook matches brief', 'claims are supportable', 'platform specs pass', 'multiple variants produced', 'performance feedback recorded'], evidenceRequirements: ['script', 'storyboard', 'render metadata', 'QA notes', 'analytics after launch'], failureSignals: ['unclear CTA', 'unsupported claim', 'poor visual continuity', 'format mismatch'], repairStrategy: 'retry' },
    modelPolicy: router(['video-generation', 'multimodal-review', 'copy', 'editing'], 'Provider-neutral creative routing: select by quality, cost, duration, aspect ratio, rights and availability.'),
  },
];

export function getSuperAgentDefinition(id: string): SuperAgentDefinition | undefined {
  return SUPER_AGENT_DEFINITIONS.find((agent) => agent.id === id);
}

export function getSuperAgentsByDepartment(department: string): SuperAgentDefinition[] {
  return SUPER_AGENT_DEFINITIONS.filter((agent) => agent.department === department);
}
