'use client';

import { useState } from 'react';
import { ArrowDown, ArrowUp, Check, Eye, LayoutTemplate, Palette, Plus, Sparkles, Trash2, Wand2 } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { Badge, SectionHead } from '@/components/terminal';
import { STYLE_DIRECTIONS, tasteAudit } from '@/lib/design-intelligence';
import { WebsiteBuilderTools } from '@/components/WebsiteBuilderTools';
import { ProjectSwitcher } from '@/components/ProjectSwitcher';
import { TemplateVault } from '@/components/TemplateVault';
import type { VaultTemplate } from '@/lib/template-vault';

const templates = ['Creator landing page', 'SaaS launch page', 'Agency homepage', 'Lead magnet funnel'];
const DEFAULT_BLOCKS = ['Hero', 'Social proof', 'Feature grid', 'Offer / CTA', 'FAQ', 'Footer'];

export default function WebsiteBuilderPage() {
  const [prompt, setPrompt] = useState('A premium, editorial landing page for a founder-led AI automation studio');
  const [title, setTitle] = useState('Build the system behind your next chapter.');
  const [generated, setGenerated] = useState(false);
  const [published, setPublished] = useState(false);
  const [uploadStatus, setUploadStatus] = useState('');
  const [assetFolder, setAssetFolder] = useState('general');
  const [aiStatus, setAiStatus] = useState('');
  const [direction, setDirection] = useState('editorial');
  const [projectId, setProjectId] = useState<string | undefined>();
  const [blocks, setBlocks] = useState(DEFAULT_BLOCKS);
  const [draggedBlock, setDraggedBlock] = useState<string | null>(null);
  const audit = tasteAudit({ title, sections: blocks.length, cta: 'See how it works', direction });
  const addBlock = (block: string) => setBlocks((current) => current.includes(block) ? current : [...current, block]);
  const moveBlock = (index: number, delta: number) => setBlocks((current) => { const target = index + delta; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const dropBlock = (target: string) => { if (!draggedBlock || draggedBlock === target) return; setBlocks((current) => { const from = current.indexOf(draggedBlock); const to = current.indexOf(target); if (from < 0 || to < 0) return current; const next = [...current]; next.splice(from, 1); next.splice(to, 0, draggedBlock); return next; }); setDraggedBlock(null); };
  const applyTemplate = (template: VaultTemplate) => { setPrompt(`${template.description} Use ${template.styles.join(', ')} styling with ${template.components.join(', ')}.`); setBlocks(template.components); setGenerated(false); };
  const loadProject = (project: { id?: string; name: string; prompt?: string; direction?: string; page?: { title?: string; blocks?: string[]; generated?: boolean } }) => { setProjectId(project.id); setTitle(project.page?.title || project.name); setPrompt(project.prompt || ''); setDirection(project.direction || 'editorial'); setBlocks(project.page?.blocks?.length ? project.page.blocks : DEFAULT_BLOCKS); setGenerated(Boolean(project.page?.generated)); };

  return <div>
    <PageHeader eyebrow="creative / web" title="Website Builder" right={<Badge tone="ok">● keyless studio</Badge>} />
    <div className="mb-6 flex flex-wrap gap-2">
      {templates.map((t) => <button key={t} onClick={() => { setPrompt(`A ${t.toLowerCase()} with a confident, high-converting visual system`); setGenerated(false); }} className="flex items-center gap-2 rounded-sm-t border border-os-border bg-os-surface px-3 py-2 font-mono text-[10px] uppercase tracking-[0.1em] hover:border-[var(--accent-line)]"><LayoutTemplate className="h-3.5 w-3.5 text-os-accent" />{t}</button>)}
    </div>
    <div className="mb-6"><ProjectSwitcher onLoad={loadProject} /></div>
    <TemplateVault onSelect={applyTemplate} />
      <section className="mb-6"><SectionHead label="Design intelligence" count={aiStatus || 'anti-generic controls'} /><div className="grid gap-2 md:grid-cols-4">{STYLE_DIRECTIONS.map((style) => <button key={style.id} onClick={() => setDirection(style.id)} className={`rounded-lg-t border px-3 py-3 text-left ${direction === style.id ? 'border-[var(--accent-line)] bg-os-accent/10' : 'border-os-border bg-os-surface hover:bg-os-surface2'}`}><div className="text-[12px] font-semibold">{style.name}</div><div className="mt-1 font-mono text-[9px] uppercase text-os-dim">{style.font}</div><div className="mt-2 text-[10px] leading-relaxed text-os-muted">{style.rule}</div></button>)}</div><button onClick={async () => { const r = await fetch('/api/ai/design-brief', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt, direction }) }); const body = await r.json(); setAiStatus(`${body.brief.sections.length} sections · ${body.brief.rules.length} taste rules`); setGenerated(true); }} className="mt-3 flex items-center gap-2 rounded-sm-t border border-os-border bg-os-surface px-3 py-2 font-mono text-[10px] uppercase hover:bg-os-surface2"><Sparkles className="h-3.5 w-3.5 text-os-accent" /> Run smart design brief</button></section>
    <div className="grid gap-5 xl:grid-cols-[260px_minmax(500px,1fr)_260px]">
      <aside className="space-y-4">
        <section><SectionHead label="Asset library" count="local folder" /><div className="rounded-lg-t border border-os-border bg-os-surface p-3"><select value={assetFolder} onChange={e => setAssetFolder(e.target.value)} className="mb-2 w-full rounded-sm-t border border-os-border bg-os-surface2 px-2 py-2 font-mono text-[10px] uppercase"><option value="general">General</option><option value="brand">Brand</option><option value="website">Website</option><option value="social">Social</option><option value="client">Client files</option></select><label className="flex cursor-pointer items-center justify-center gap-2 rounded-sm-t border border-dashed border-os-border-strong px-3 py-4 font-mono text-[10px] uppercase text-os-accent hover:bg-os-surface2"><Plus className="h-3.5 w-3.5" /> Upload images, ZIPs, files<input type="file" multiple className="hidden" onChange={async (e) => { const files = Array.from(e.target.files ?? []); for (const file of files) { const body = new FormData(); body.append('file', file); body.append('folder', assetFolder); const res = await fetch('/api/assets', { method: 'POST', body }); if (res.ok) setUploadStatus(`${files.length} file${files.length === 1 ? '' : 's'} saved to ${assetFolder}`); } e.target.value = ''; }} /></label>{uploadStatus && <div className="mt-2 font-mono text-[10px] text-os-ok">✓ {uploadStatus}</div>}<div className="mt-2 font-mono text-[9px] leading-relaxed text-os-dim">Up to 500MB per file. Saved locally in data/assets and excluded from git.</div></div></section>
        <section><SectionHead label="AI brief" /><div className="rounded-lg-t border border-os-border bg-os-surface p-3"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} className="h-28 w-full resize-none bg-transparent text-[12px] leading-relaxed outline-none" /><button onClick={() => setGenerated(true)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-sm-t bg-os-accent px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-[0.1em] text-[var(--accent-ink)]"><Wand2 className="h-3.5 w-3.5" /> Generate page</button></div></section>
        <section><SectionHead label="Blocks" count={`${blocks.length} active`} /><div className="space-y-1">{['Hero', 'Social proof', 'Feature grid', 'Offer / CTA', 'FAQ', 'Footer', 'Testimonials', 'Pricing', 'Contact'].map((b) => <button key={b} onClick={() => addBlock(b)} disabled={blocks.includes(b)} className="flex w-full items-center gap-2 rounded-sm-t border border-os-border bg-os-surface px-3 py-2 text-left text-[12px] hover:bg-os-surface2 disabled:cursor-not-allowed disabled:opacity-40"><Plus className="h-3.5 w-3.5 text-os-accent" />{b}</button>)}</div><div className="mt-3 space-y-1 border-t border-os-border pt-3">{blocks.map((block, index) => <div key={`${block}-${index}`} draggable onDragStart={() => setDraggedBlock(block)} onDragOver={(event) => event.preventDefault()} onDrop={() => dropBlock(block)} className={`flex items-center gap-1 rounded-sm-t border border-os-border bg-os-surface2 px-2 py-1.5 ${draggedBlock === block ? 'opacity-40' : ''}`}><span className="flex-1 cursor-grab truncate text-[11px]">⠿ {block}</span><button aria-label={`Move ${block} up`} onClick={() => moveBlock(index, -1)} disabled={index === 0} className="p-1 text-os-dim hover:text-os-accent disabled:opacity-30"><ArrowUp className="h-3 w-3" /></button><button aria-label={`Move ${block} down`} onClick={() => moveBlock(index, 1)} disabled={index === blocks.length - 1} className="p-1 text-os-dim hover:text-os-accent disabled:opacity-30"><ArrowDown className="h-3 w-3" /></button><button aria-label={`Remove ${block}`} onClick={() => setBlocks((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="p-1 text-os-dim hover:text-os-warn"><Trash2 className="h-3 w-3" /></button></div>)}</div><div className="mt-2 font-mono text-[9px] text-os-dim">Drag a block row to change its order.</div></section>
      </aside>
      <main className="overflow-hidden rounded-lg-t border border-os-border bg-os-surface">
        <div className="flex items-center justify-between border-b border-os-border px-4 py-2"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.15em] text-os-dim"><Eye className="h-3.5 w-3.5" /> Live preview · desktop</div><div className="flex gap-2"><button className="rounded-sm-t border border-os-border px-2 py-1 font-mono text-[9px] uppercase">Mobile</button><button onClick={() => setPublished(true)} className="rounded-sm-t bg-os-accent px-2 py-1 font-mono text-[9px] font-bold uppercase text-[var(--accent-ink)]">{published ? 'Published' : 'Publish draft'}</button></div></div>
        <div className="min-h-[650px] bg-[#f4f0e7] px-[8%] py-14 text-[#1c211d]"><div className="mx-auto max-w-3xl"><div className="flex items-center justify-between text-[11px] font-bold tracking-[0.14em]"><span>FOUNDER / STUDIO</span><span className="rounded-full border border-[#1c211d]/20 px-3 py-1 text-[9px]">WORK WITH US ↗</span></div><div className="mt-24 max-w-2xl"><div className="mb-5 font-mono text-[10px] uppercase tracking-[0.2em] text-[#718074]">Independent systems · 2026</div><input value={title} onChange={(e) => setTitle(e.target.value)} className="w-full bg-transparent font-serif text-[clamp(42px,6vw,78px)] leading-[0.94] tracking-[-0.05em] outline-none" /><p className="mt-8 max-w-lg text-[17px] leading-relaxed text-[#566159]">We design practical operating systems, sharp brands, and calm growth engines for ambitious small teams.</p><button className="mt-9 rounded-full bg-[#1c211d] px-6 py-3 text-[12px] font-bold text-[#f4f0e7]">See how it works ↗</button></div><div className="mt-32 grid grid-cols-3 gap-3 border-t border-[#1c211d]/15 pt-5 text-[10px] uppercase tracking-[0.12em] text-[#718074]"><span>Strategy</span><span>Design</span><span>Systems</span></div></div></div>
      </main>
      <aside className="space-y-4"><SectionHead label="Taste audit" count={`${audit.score}/100`} /><div className="rounded-lg-t border border-os-border bg-os-surface p-3">{audit.checks.map(({ label, pass }) => <div key={label} className="flex items-center justify-between border-b border-os-border py-3 last:border-0"><span className="text-[12px]">{label}</span><span className={`flex items-center gap-1 font-mono text-[10px] uppercase ${pass ? 'text-os-ok' : 'text-os-warn'}`}>{pass ? <Check className="h-3 w-3" /> : <Sparkles className="h-3 w-3" />}{pass ? 'Pass' : 'Review'}</span></div>)}</div><SectionHead label="Export" /><WebsiteBuilderTools projectId={projectId} prompt={prompt} title={title} direction={direction} blocks={blocks} generated={generated} />{generated && <div className="rounded-sm-t border border-[var(--accent-line)] bg-os-accent/5 p-3 font-mono text-[10px] text-os-accent">✓ Page generated in demo mode. Add an AI key to replace the seeded copy.</div>}</aside>
    </div>
  </div>;
}
