'use client';
import { useEffect, useState } from 'react';
import { ConciergePanel } from '@/components/ConciergePanel';

export function BlueprintPanel({ summary, missing }: { summary: string[]; missing: string[] }) {
  const [proposal, setProposal] = useState(''); const [saved, setSaved] = useState(false);
  useEffect(() => setProposal(localStorage.getItem('business-os-blueprint-proposal') || ''), []);
  const save = () => { localStorage.setItem('business-os-blueprint-proposal', proposal); setSaved(true); };
  return <><section className="mb-9 rounded-lg-t border border-[var(--accent-line)] bg-os-accent/5 p-5"><div className="font-mono text-[11px] uppercase tracking-widest text-os-accent">Business blueprint · live copy</div><h2 className="mt-1 text-[20px] font-semibold">How the business OS is structured</h2><p className="mt-2 text-sm leading-6 text-os-muted">This blueprint is the shared operating reference for G-Brain, the specialist agents, the website, affiliate research, content, social publishing, analytics, and finance. It is generated from the current roster and connector checks.</p><div className="mt-4 grid gap-2 md:grid-cols-2">{summary.map(item => <div key={item} className="rounded-sm-t border border-os-border bg-os-surface p-3 text-sm">✓ {item}</div>)}{missing.map(item => <div key={item} className="rounded-sm-t border border-os-border bg-os-surface p-3 text-sm text-os-warn">○ {item}</div>)}</div></section><section className="mb-9 rounded-lg-t border border-os-border bg-os-surface p-5"><div className="font-mono text-[11px] uppercase tracking-widest text-os-accent">Blueprint proposals</div><p className="mt-2 text-sm text-os-muted">Write proposed additions or changes here. They are isolated from the live system until you review and approve them.</p><textarea value={proposal} onChange={e => { setProposal(e.target.value); setSaved(false); }} placeholder="Propose a new agent, skill, connector, or workflow…" className="mt-3 min-h-24 w-full rounded-sm-t border border-os-border bg-transparent p-3 text-sm outline-none" /><button type="button" onClick={save} className="mt-2 rounded-sm-t border border-os-border px-3 py-2 font-mono text-[11px] uppercase text-os-accent">{saved ? 'Proposal saved' : 'Save proposal'}</button></section><ConciergePanel /></>;
}
