'use client';
import { useEffect, useState } from 'react';

type Draft = { id: string; title: string; date: string; notes: string };
const KEY = 'business-os-calendar-drafts';
export function CalendarPlanner() {
  const [open, setOpen] = useState(false); const [drafts, setDrafts] = useState<Draft[]>([]); const [title, setTitle] = useState(''); const [date, setDate] = useState(''); const [notes, setNotes] = useState('');
  useEffect(() => { try { setDrafts(JSON.parse(localStorage.getItem(KEY) || '[]')); } catch { setDrafts([]); } }, []);
  const add = () => { if (!title.trim() || !date) return; const next = [{ id: crypto.randomUUID(), title: title.trim(), date, notes: notes.trim() }, ...drafts]; setDrafts(next); localStorage.setItem(KEY, JSON.stringify(next)); setTitle(''); setDate(''); setNotes(''); setOpen(false); };
  return <section className="mb-6 rounded-lg-t border border-os-border bg-os-surface p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-[17px] font-semibold">Marketing planning</h2><p className="mt-1 text-sm text-os-muted">Add local planning drafts for the marketing agent. Google events remain read live from the connected calendar.</p></div><button type="button" onClick={() => setOpen(!open)} className="rounded-sm-t border border-os-border px-3 py-2 font-mono text-[11px] uppercase text-os-accent">{open ? 'Cancel' : '+ Add event'}</button></div>{open && <div className="mt-4 grid gap-2 md:grid-cols-4"><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Campaign or review title" className="rounded-sm-t border border-os-border bg-transparent p-2 text-sm md:col-span-2" /><input type="datetime-local" value={date} onChange={e => setDate(e.target.value)} className="rounded-sm-t border border-os-border bg-transparent p-2 text-sm" /><button type="button" onClick={add} disabled={!title.trim() || !date} className="rounded-sm-t bg-os-accent p-2 font-mono text-[11px] uppercase text-os-ink disabled:opacity-40">Save draft</button><input value={notes} onChange={e => setNotes(e.target.value)} placeholder="Notes for the agent (optional)" className="rounded-sm-t border border-os-border bg-transparent p-2 text-sm md:col-span-4" /></div>}{drafts.length > 0 && <div className="mt-4 space-y-2">{drafts.slice(0, 5).map(d => <div key={d.id} className="flex flex-wrap justify-between gap-2 rounded-sm-t border border-os-border bg-os-surface2 p-3 text-sm"><span className="font-semibold">{d.title}</span><span className="font-mono text-[11px] text-os-accent">{new Date(d.date).toLocaleString()}</span></div>)}</div>}<p className="mt-3 font-mono text-[10px] text-os-dim">Planning drafts stay in this browser until Google Calendar write access is authorized.</p></section>;
}
