'use client';

import { useEffect, useState } from 'react';
import { Layers, Sparkles } from 'lucide-react';
import type { VaultTemplate } from '@/lib/template-vault';

export function TemplateVault({ onSelect }: { onSelect: (template: VaultTemplate) => void }) {
  const [templates, setTemplates] = useState<VaultTemplate[]>([]); const [kind, setKind] = useState('all'); const [selected, setSelected] = useState('');
  useEffect(() => { const load = () => { fetch('/api/templates').then(r => r.ok ? r.json() : { templates: [] }).then(b => { let custom: VaultTemplate[] = []; try { const saved = JSON.parse(window.localStorage.getItem('business-os-custom-templates') || '[]'); if (Array.isArray(saved)) custom = saved.filter((item): item is VaultTemplate => item && typeof item.id === 'string' && typeof item.name === 'string' && Array.isArray(item.components)); } catch { window.localStorage.removeItem('business-os-custom-templates'); } setTemplates([...custom, ...(b.templates ?? [])]); }).catch(() => undefined); }; load(); window.addEventListener('business-os-templates-changed', load); return () => window.removeEventListener('business-os-templates-changed', load); }, []);
  const visible = templates.filter(t => kind === 'all' || t.kind === kind);
  return <section className="mb-6"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2"><Layers className="h-4 w-4 text-os-accent" /><span className="font-mono text-[10px] uppercase tracking-[0.15em] text-os-dim">Template Vault</span></div><select aria-label="Filter templates" value={kind} onChange={e => setKind(e.target.value)} className="rounded-sm-t border border-os-border bg-os-surface px-2 py-1 font-mono text-[9px] uppercase"><option value="all">All systems</option><option value="frontend">Frontend</option><option value="backend">Backend</option><option value="full-stack">Full stack</option></select></div><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{visible.map(template => <button key={template.id} onClick={() => { setSelected(template.id); onSelect(template); }} className={`rounded-lg-t border p-3 text-left ${selected === template.id ? 'border-[var(--accent-line)] bg-os-accent/10' : 'border-os-border bg-os-surface hover:bg-os-surface2'}`}><div className="flex items-center justify-between"><span className="text-[12px] font-semibold">{template.name}</span><span className="font-mono text-[8px] uppercase text-os-dim">{template.kind}</span></div><p className="mt-2 text-[10px] leading-relaxed text-os-muted">{template.description}</p><div className="mt-2 flex flex-wrap gap-1">{template.styles.map(style => <span key={style} className="rounded-sm-t border border-os-border px-1.5 py-0.5 font-mono text-[8px] uppercase text-os-dim">{style}</span>)}</div><div className="mt-3 flex items-center gap-1 font-mono text-[9px] uppercase text-os-accent"><Sparkles className="h-3 w-3" /> {template.components.length} component recipes · {template.animation}</div></button>)}</div></section>;
}
