'use client';

import { useEffect, useState } from 'react';
import { ExternalLink, Eye, Layers, Sparkles } from 'lucide-react';
import type { VaultTemplate } from '@/lib/template-vault';

export function TemplateVault({ onSelect }: { onSelect: (template: VaultTemplate) => void }) {
  const [templates, setTemplates] = useState<VaultTemplate[]>([]); const [kind, setKind] = useState('all'); const [selected, setSelected] = useState(''); const [preview, setPreview] = useState<VaultTemplate | null>(null);
  useEffect(() => { const load = () => { fetch('/api/templates').then(r => r.ok ? r.json() : { templates: [] }).then(b => { let custom: VaultTemplate[] = []; try { const saved = JSON.parse(window.localStorage.getItem('business-os-custom-templates') || '[]'); if (Array.isArray(saved)) custom = saved.filter((item): item is VaultTemplate => item && typeof item.id === 'string' && typeof item.name === 'string' && Array.isArray(item.components)); } catch { window.localStorage.removeItem('business-os-custom-templates'); } setTemplates([...custom, ...(b.templates ?? [])]); }).catch(() => undefined); }; load(); window.addEventListener('business-os-templates-changed', load); return () => window.removeEventListener('business-os-templates-changed', load); }, []);
  const visible = templates.filter(t => kind === 'all' || t.kind === kind);
  return <section className="mb-6">
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Layers className="h-4 w-4 text-os-accent" /><span className="font-mono text-[10px] uppercase tracking-[0.15em] text-os-dim">Template Vault</span><span className="font-mono text-[9px] text-os-accent">{visible.length} available</span></div><select aria-label="Filter templates" value={kind} onChange={e => setKind(e.target.value)} className="rounded-sm-t border border-os-border bg-os-surface px-2 py-1 font-mono text-[9px] uppercase"><option value="all">All systems</option><option value="frontend">Frontend</option><option value="backend">Backend</option><option value="full-stack">Full stack</option></select></div>
    <div className="mb-3 rounded-lg-t border border-os-accent/30 bg-os-accent/5 px-3 py-3 text-[11px] leading-relaxed text-os-muted"><span className="font-semibold text-os-accent">FreeTemplateGo collection.</span> Twenty multi-page HTML/Tailwind starting points are available here as design references. Use one to seed the AI brief, inspect its live demo, or open the source. Replace demo imagery with rights-cleared assets before publishing.</div>
    <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{visible.map(template => <div key={template.id} className={`rounded-lg-t border p-3 text-left ${selected === template.id ? 'border-[var(--accent-line)] bg-os-accent/10' : 'border-os-border bg-os-surface hover:bg-os-surface2'}`}><button type="button" onClick={() => { setSelected(template.id); onSelect(template); }} className="w-full text-left"><div className="flex items-center justify-between"><span className="text-[12px] font-semibold">{template.name}</span><span className="font-mono text-[8px] uppercase text-os-dim">{template.kind}</span></div><p className="mt-2 text-[10px] leading-relaxed text-os-muted">{template.description}</p><div className="mt-2 flex flex-wrap gap-1">{template.styles.map(style => <span key={style} className="rounded-sm-t border border-os-border px-1.5 py-0.5 font-mono text-[8px] uppercase text-os-dim">{style}</span>)}</div><div className="mt-3 flex items-center gap-1 font-mono text-[9px] uppercase text-os-accent"><Sparkles className="h-3 w-3" /> {template.pageCount ? `${template.pageCount} pages · ` : ''}{template.components.length} component recipes</div></button><div className="mt-3 flex flex-wrap gap-2 border-t border-os-border pt-2"><button type="button" onClick={() => setPreview(template)} disabled={!template.previewUrl} className="flex items-center gap-1 rounded-sm-t border border-os-border px-2 py-1 font-mono text-[9px] uppercase text-os-accent hover:bg-os-surface2 disabled:opacity-40"><Eye className="h-3 w-3" /> Preview</button>{template.sourceUrl && <a href={template.sourceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-sm-t border border-os-border px-2 py-1 font-mono text-[9px] uppercase text-os-muted hover:text-os-accent"><ExternalLink className="h-3 w-3" /> Source</a>}</div>{template.license && <div className="mt-2 font-mono text-[8px] leading-relaxed text-os-dim">{template.license}</div>}</div>)}</div>
    {preview?.previewUrl && <div className="mt-4 overflow-hidden rounded-lg-t border border-[var(--accent-line)] bg-os-surface"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-os-border px-3 py-2"><div><div className="font-mono text-[10px] uppercase tracking-[0.12em] text-os-accent">Template preview · {preview.name}</div><div className="mt-1 text-[10px] text-os-muted">Reference only. Use the source or the card action to start a working draft.</div></div><div className="flex items-center gap-2"><a href={preview.previewUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 font-mono text-[9px] uppercase text-os-muted hover:text-os-accent">Open demo <ExternalLink className="h-3 w-3" /></a><button type="button" onClick={() => setPreview(null)} className="border border-os-border px-2 py-1 font-mono text-[9px] uppercase text-os-muted hover:text-os-accent">Close</button></div></div><iframe title={`${preview.name} live demo`} src={preview.previewUrl} className="h-[620px] w-full border-0 bg-white" /></div>}
  </section>;
}
